# Copyright (c) HashiCorp, Inc.

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
