# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: test
# Description: user description for task named 'test'

testProvider = {
  alias = "tp"
  attr  = "value"
  count = 10
}

services = {
}
