# This file is generated by Consul NIA.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Consul NIA. Any manual changes to this file
# may not be preserved and could be clobbered by a subsequent update.

testProvider = {
  alias = "tp"
  attr  = "value"
  count = 10
}

services = {
  "api" : {
    name        = "api"
    description = "api service for web"
    addresses = [
      {
        address = "1.2.3.4"
        port    = 8080
      },
      {
        address = "5.6.7.8"
        port    = 8080
      }
    ]
  },
  "web" : {
    name        = "web"
    description = "web service"
    addresses = [
      {
        address = "1.1.1.1"
        port    = 8000
      }
    ]
  }
}
