# This file is generated by Consul-Terraform-Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Consul-Terraform-Sync. Any manual changes to
# this file may not be preserved and could be overwritten by a subsequent
# update.
#
# Task: test
# Description: user description for task named 'test'

b   = true
key = "some_key"
l   = [4, 0]
num = 10
obj = {
  argList = ["a", "b", "c"]
  argMap  = {}
  argNum  = -0.52
  argStr  = "value"
}
tup = ["abc", 123, false]

