# This file is generated by Consul NIA.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Consul NIA. Any manual changes to this file
# may not be preserved and could be clobbered by a subsequent update.


variable "b" {
  default = []
  type    = bool
}

variable "key" {
  default = []
  type    = string
}

variable "l" {
  default = []
  type    = list(any)
}

variable "num" {
  default = []
  type    = number
}

variable "obj" {
  default = []
  type = object({
    argList = list(any)
    argMap  = map(any)
    argNum  = number
    argStr  = string
  })
}

variable "tup" {
  default = []
  type    = tuple([string, number, bool])
}
