# This file is generated by Consul-Terraform-Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Consul-Terraform-Sync. Any manual changes to
# this file may not be preserved and could be overwritten by a subsequent
# update.
#
# Task: my-task
# Description: automate services for website X

myprovider = {
  address  = "myprovider.example.com"
  attr     = "foobar"
  username = "admin"
}
