// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Overrider is an autogenerated mock type for the Overrider type
type Overrider struct {
	mock.Mock
}

// Override provides a mock function with given fields:
func (_m *Overrider) Override() {
	_m.Called()
}

// NewOverrider creates a new instance of Overrider. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewOverrider(t testing.TB) *Overrider {
	mock := &Overrider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
