// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Overrider is an autogenerated mock type for the Overrider type
type Overrider struct {
	mock.Mock
}

// Override provides a mock function with given fields:
func (_m *Overrider) Override() {
	_m.Called()
}
