// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Overrider is an autogenerated mock type for the Overrider type
type Overrider struct {
	mock.Mock
}

// Override provides a mock function with given fields:
func (_m *Overrider) Override() {
	_m.Called()
}

type mockConstructorTestingTNewOverrider interface {
	mock.TestingT
	Cleanup(func())
}

// NewOverrider creates a new instance of Overrider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOverrider(t mockConstructorTestingTNewOverrider) *Overrider {
	mock := &Overrider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
