# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be clobbered by a subsequent update.

terraform {
  required_version = ">= 0.13.0, < 0.15"
  required_providers {
    myprovider = {
      source  = "namespace/myprovider"
      version = "1.3.0"
    }
  }
  backend "consul" {
    address = "consul.example.com"
    gzip    = true
    path    = "consul-terraform-sync/terraform"
  }
}

provider "myprovider" {
  address  = var.myprovider.address
  attr     = var.myprovider.attr
  username = var.myprovider.username
}

# automate services for website X
module "my-task" {
  source   = "namespace/example/module"
  version  = "1.0.0"
  services = var.services

  enabled = var.enabled
  format  = var.format
  tags    = var.tags
  count   = var.count
}
