# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: my-task
# Description: automate services for website X

variable "count" {
  default = null
  type    = number
}

variable "enabled" {
  default = null
  type    = bool
}

variable "format" {
  default = null
  type    = string
}

variable "tags" {
  default = null
  type    = tuple([string, string])
}
